# Generated by Django 5.1.4 on 2024-12-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_teacher_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.AutoField(default=-999, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
