# Generated by Django 5.1.4 on 2024-12-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_studentprofile_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_id',
            field=models.AutoField(default=-999, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
