# Generated by Django 4.2.9 on 2026-02-01 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_coursemodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='courses.course')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='courses.coursemodule')),
            ],
            options={
                'db_table': 'pages',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['course'], name='pages_course__75a048_idx'), models.Index(fields=['module'], name='pages_module__1c0f70_idx'), models.Index(fields=['is_published'], name='pages_is_publ_b61b27_idx')],
            },
        ),
    ]
