
services:
  backend:
    build: ./backend
    container_name: syllabex-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: syllabex-frontend
    command: npm run dev     # or npm run start if you're doing production
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
