# Generated by Django 4.2.9 on 2026-01-22 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('graded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('comments', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assignments.assignment')),
                ('graded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_given', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.coursemembership')),
            ],
            options={
                'verbose_name': 'Grade Entry',
                'verbose_name_plural': 'Grade Entries',
                'db_table': 'grade_entries',
                'ordering': ['-graded_at'],
                'indexes': [models.Index(fields=['membership'], name='grade_entri_members_a2d51d_idx'), models.Index(fields=['assignment'], name='grade_entri_assignm_7ad5d0_idx'), models.Index(fields=['graded_at'], name='grade_entri_graded__49ec55_idx')],
                'unique_together': {('membership', 'assignment')},
            },
        ),
    ]
