# Generated by Django 4.2.9 on 2026-01-29 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('graded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('comments', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assignments.assignment')),
            ],
            options={
                'verbose_name': 'Grade Entry',
                'verbose_name_plural': 'Grade Entries',
                'db_table': 'grade_entries',
                'ordering': ['-graded_at'],
            },
        ),
    ]
