# Generated by Django 4.2.9 on 2026-01-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('gradebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeentry',
            name='graded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_given', to='users.teacherprofile'),
        ),
        migrations.AddIndex(
            model_name='gradeentry',
            index=models.Index(fields=['enrollment'], name='grade_entri_enrollm_e0d379_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeentry',
            index=models.Index(fields=['assignment'], name='grade_entri_assignm_7ad5d0_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeentry',
            index=models.Index(fields=['graded_at'], name='grade_entri_graded__49ec55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradeentry',
            unique_together={('enrollment', 'assignment')},
        ),
    ]
