# Generated by Django 4.2.9 on 2026-01-29 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gradebook', '0001_initial'),
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeentry',
            name='graded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradeentry',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.coursemembership'),
        ),
        migrations.AddIndex(
            model_name='gradeentry',
            index=models.Index(fields=['membership'], name='grade_entri_members_a2d51d_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeentry',
            index=models.Index(fields=['assignment'], name='grade_entri_assignm_7ad5d0_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeentry',
            index=models.Index(fields=['graded_at'], name='grade_entri_graded__49ec55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradeentry',
            unique_together={('membership', 'assignment')},
        ),
    ]
