# Generated by Django 4.2.9 on 2026-01-22 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor')], db_index=True, default='student', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dropped', 'Dropped'), ('completed', 'Completed')], db_index=True, default='active', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Membership',
                'verbose_name_plural': 'Course Memberships',
                'db_table': 'course_memberships',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='courses_code_fa42f1_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='courses_is_acti_25e634_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemembership',
            index=models.Index(fields=['user'], name='course_memb_user_id_16908c_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemembership',
            index=models.Index(fields=['course'], name='course_memb_course__526004_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemembership',
            index=models.Index(fields=['role'], name='course_memb_role_9f5c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemembership',
            index=models.Index(fields=['status'], name='course_memb_status_d3cdf9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursemembership',
            unique_together={('user', 'course')},
        ),
    ]
