# Generated by Django 4.2.9 on 2026-01-29 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.account'),
        ),
        migrations.AddIndex(
            model_name='coursemembership',
            index=models.Index(fields=['user'], name='course_memb_user_id_16908c_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemembership',
            index=models.Index(fields=['course'], name='course_memb_course__526004_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemembership',
            index=models.Index(fields=['role'], name='course_memb_role_9f5c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemembership',
            index=models.Index(fields=['status'], name='course_memb_status_d3cdf9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursemembership',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='courses_code_fa42f1_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='courses_is_acti_25e634_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'account')},
        ),
    ]
