# Generated by Django 4.2.9 on 2026-01-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_course_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ai_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
