# Generated by Django 4.2.9 on 2026-01-29 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('assignments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course'),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homework',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assignments.assignment',),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assignments.assignment',),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assignments.assignment',),
        ),
        migrations.AddIndex(
            model_name='questionresponse',
            index=models.Index(fields=['submission'], name='question_re_submiss_8045a8_idx'),
        ),
        migrations.AddIndex(
            model_name='questionresponse',
            index=models.Index(fields=['question'], name='question_re_questio_70313b_idx'),
        ),
        migrations.AddIndex(
            model_name='questionresponse',
            index=models.Index(fields=['graded'], name='question_re_graded_32be42_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionresponse',
            unique_together={('submission', 'question')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['assignment'], name='questions_assignm_65a685_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='questions_questio_8af709_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['order'], name='questions_order_2c3df8_idx'),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['question'], name='choices_questio_436020_idx'),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['order'], name='choices_order_8d6754_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment'], name='assignment__assignm_df300a_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['student'], name='assignment__student_f0cb4e_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['submitted_at'], name='assignment__submitt_040795_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course'], name='assignments_course__383e45_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['type'], name='assignments_type_86bb18_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['start_date'], name='assignments_start_d_453408_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='assignments_due_dat_708d3b_idx'),
        ),
    ]
