# Generated by Django 4.2.9 on 2026-01-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('assignments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course'),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homework',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assignments.assignment',),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assignments.assignment',),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assignments.assignment',),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment'], name='assignment__assignm_df300a_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['student'], name='assignment__student_f0cb4e_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['submitted_at'], name='assignment__submitt_040795_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course'], name='assignments_course__383e45_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['type'], name='assignments_type_86bb18_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='assignments_due_dat_708d3b_idx'),
        ),
    ]
