# Generated by Django 4.2.9 on 2026-01-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='teacher_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['start_date'], name='assignments_start_d_453408_idx'),
        ),
    ]
