# Generated by Django 4.2.9 on 2026-01-22 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('numerical', 'Numerical'), ('text_response', 'Text Response')], db_index=True, max_length=20)),
                ('text', models.TextField()),
                ('points', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('correct_answer_numeric', models.FloatField(blank=True, null=True)),
                ('numeric_tolerance', models.FloatField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.assignment')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'questions',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assignments.question')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
                'db_table': 'choices',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True, default='')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_earned', models.IntegerField(blank=True, null=True)),
                ('graded', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assignments.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='assignments.assignmentsubmission')),
            ],
            options={
                'verbose_name': 'Question Response',
                'verbose_name_plural': 'Question Responses',
                'db_table': 'question_responses',
                'indexes': [models.Index(fields=['submission'], name='question_re_submiss_8045a8_idx'), models.Index(fields=['question'], name='question_re_questio_70313b_idx'), models.Index(fields=['graded'], name='question_re_graded_32be42_idx')],
                'unique_together': {('submission', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['assignment'], name='questions_assignm_65a685_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='questions_questio_8af709_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['order'], name='questions_order_2c3df8_idx'),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['question'], name='choices_questio_436020_idx'),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['order'], name='choices_order_8d6754_idx'),
        ),
    ]
