# Generated by Django 4.2.9 on 2026-02-01 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0001_initial'),
        ('assignments', '0003_assignment_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='rubrics.rubric'),
        ),
    ]
