# Generated by Django 4.2.9 on 2026-02-01 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0003_assignment_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_coursemodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_reusable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rubrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rubrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RubricAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('graded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubric_assessments_given', to=settings.AUTH_USER_MODEL)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='rubrics.rubric')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_assessments', to='assignments.assignmentsubmission')),
            ],
            options={
                'db_table': 'rubric_assessments',
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('points_possible', models.IntegerField()),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='rubrics.rubric')),
            ],
            options={
                'db_table': 'rubric_criteria',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RubricRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('points', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rubrics.rubriccriterion')),
            ],
            options={
                'db_table': 'rubric_ratings',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RubricCriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, default='')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='rubrics.rubricassessment')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='rubrics.rubriccriterion')),
                ('selected_rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='rubrics.rubricrating')),
            ],
            options={
                'db_table': 'rubric_criterion_scores',
            },
        ),
        migrations.AddIndex(
            model_name='rubricrating',
            index=models.Index(fields=['criterion'], name='rubric_rati_criteri_a9edf2_idx'),
        ),
        migrations.AddIndex(
            model_name='rubricrating',
            index=models.Index(fields=['order'], name='rubric_rati_order_c0ed78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rubricrating',
            unique_together={('criterion', 'order')},
        ),
        migrations.AddIndex(
            model_name='rubriccriterionscore',
            index=models.Index(fields=['assessment'], name='rubric_crit_assessm_c332d5_idx'),
        ),
        migrations.AddIndex(
            model_name='rubriccriterionscore',
            index=models.Index(fields=['criterion'], name='rubric_crit_criteri_14427a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rubriccriterionscore',
            unique_together={('assessment', 'criterion')},
        ),
        migrations.AddIndex(
            model_name='rubriccriterion',
            index=models.Index(fields=['rubric'], name='rubric_crit_rubric__7e66b7_idx'),
        ),
        migrations.AddIndex(
            model_name='rubriccriterion',
            index=models.Index(fields=['order'], name='rubric_crit_order_302aee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rubriccriterion',
            unique_together={('rubric', 'order')},
        ),
        migrations.AddIndex(
            model_name='rubricassessment',
            index=models.Index(fields=['submission'], name='rubric_asse_submiss_a8c253_idx'),
        ),
        migrations.AddIndex(
            model_name='rubricassessment',
            index=models.Index(fields=['rubric'], name='rubric_asse_rubric__3bb5f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rubricassessment',
            unique_together={('submission', 'rubric')},
        ),
        migrations.AddIndex(
            model_name='rubric',
            index=models.Index(fields=['course'], name='rubrics_course__8feee7_idx'),
        ),
    ]
